### ISSUE TITLE
Fix mozilla.ch bugs and then move it to Community IT

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/participation#16]
## Goal:

Move the mozilla.ch website to Community IT servers.
## Success:

The website is up and running on Mozilla infrastructure.
## Roles:

Owner: @MichaelKohler
Involved: @freaktechnik, @J0WI, @colinfrei 
## Required:
- [x] Fix the bugs that need to be fixed (https://github.com/mozillach/mozilla.ch/issues) (all, large, Due: 29.02.2016) 
- [x] Let Community IT redeploy the container (@MichaelKohler, small, Due: 04.03.2016) 
- [x] Let IT change the DNS A Record (@MichaelKohler, small, Due: 06.03.2016)

**Comment by MichaelKohler** [comment]
Most crucial bug: https://github.com/mozillach/mozilla.ch-docker/issues/6
Current status: http://mozillach.paas.mozilla.community

**Comment by MichaelKohler** [comment]
https://mozillach.paas.mozilla.community is now running correctly. Thanks to everyone who helped out here!

Next steps:
- Get a SSL cert for mozilla.ch (letsencrypt is not an option, since it blocks some domains, mozilla.tld are in the list)
- Point the A record to the PaaS

**Comment by MichaelKohler** [comment]
For reference, this is the SSL request bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1251768

**Comment by J0WI** [comment]
All other CAs require a specific mail address for the validation process. It's quite possible (I even hope so), that other CAs also require a manual audit for Mozilla related domains.
So sadly we can't do more here.

**Comment by MichaelKohler** [comment]
> So sadly we can't do more here.

We can't, but the Mozilla WebOps team can, so we'll eventually get one :)

**Comment by MichaelKohler** [comment]
It's currently running on a DigitalOcean droplet, we can move it once we have the SSL figured out.

Another thought: maybe we could fix mozillach/mozilla.ch#23 before that? Apart from this one, I don't see any other issue that has P1 (that is as long as tabzilla still works).

**Comment by MichaelKohler** [comment]
And yes, I meant to say mozillach/mozilla.ch#34, sorry :)

**Comment by MichaelKohler** [comment]
Unassigning me, since this one is blocked by the SSL issue

**Comment by MichaelKohler** [comment]
The PaaS is updated with our latest docker image. The DNS change has been done. This should now propagate through the internet and we don't need to do anything here. Yay!

Reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1280598
