### ISSUE TITLE
Romandie: Set a date and location for an IoT hackathon

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/participation#20]
## Goal:

Decide on a location and date for the IoT Romandie hackathon (end of March or early April)
## Success:

We have a defined date and location and can start promoting the hackathon.
## Related Issues & Links:

[meta] #12 
## Roles:

Owner: @MichaelKohler
Involved: @colinfrei @gion-andri @freaktechnik @DocZweirad @grrd01 @J0WI 
## Required:
- [ ] Define a date (due: 29.02.2016) 
- [ ] secure the location (due: 02.03.2016)

**Comment by MichaelKohler** [comment]
My recommendation would be the 2nd of April, are you available on that date?

@colinfrei what's the process regarding having the space from Liip in Lausanne? Is there a calendar as well?

**Comment by MichaelKohler** [comment]
I wonder if @gperriard is interested in this as well :)

**Comment by colinfrei** [comment]
As far as I'm aware there's no calendar, but I can check if April 2nd would work.

I'd need to be back home in the early evening on that day, but I assume that's not an issue.

**Comment by gperriard** [comment]
Hoi!
I'm definitely interested to help you.
@MichaelKohler are you available for a Firefox Hello or a skype tonight to discuss about it?

**Comment by MichaelKohler** [comment]
@gperriard not sure if we're in that state of planning yet. Let's fix a date together first and then we can work on content. Does that sound good to you?

**Comment by gperriard** [comment]
@MichaelKohler I just wanted to know more about the event itself so I can help you to find a location and people.
- What's the main goal of this hackaton? (are we gonna play around a specific tech?)
- How many people did you plan to have?
- Is it gonna be one day or more?

**Comment by MichaelKohler** [comment]
Sure, though this is not finalized yet, just an idea of mine. Please give input everybody :)

The main goal is to keep projects on IoT going. Let's imagine what we could do with the power of the Web in an IoT setting. This is basically the framing, I don't have a specific idea on that. I guess we could also let people hack on Foxbox (https://github.com/fxbox/foxbox) if they don't have an idea ready. But we should definitely encourage people to think about it before and then we can try to start hacking on it! @gperriard do you think that would work as a setting for the event?

Regarding participants, I would cap the attendees number at 15, to make sure we can have discussions and are not running around all the time to organize stuff. Do you think we could get 15 people into the Liip office? (I expect less to be honest)

It's gonna be a day, I would suggest something like 10:00 - 17:00. Ideas welcome here as well!

**Comment by loleg** [comment]
Interesting! Happy to help with platform (e.g. https://github.com/loleg/dribdat ) and data and coaching and so on.

**Comment by gperriard** [comment]
@MichaelKohler thanks for the summary.
I'm gonna check with L//P Lausanne if we could do it in their office.
Could we vote for a date?
I vote for the 2nd of April.

**Comment by MichaelKohler** [comment]
2nd of April sounds good to me, since we would have you, @loleg and @colinfrei for help. Not sure if @freaktechnik could join as well. Let's give people one more day to object and then we can schedule a meeting to discuss the content. I think we should also think about example projects we could use as a brainstorm start (as I said above, currently I don't have more than "it should be connected with IoT and the Web").

**Comment by gperriard** [comment]
Good news! We are welcome at Liip Lausanne office and it's a pleasure for them to have an hackaton there.
I'll check with them the details and secure the location once we fixed a date.

**Comment by gperriard** [comment]
Yup! Did anyone agree on the 2nd of April? :)

**Comment by MichaelKohler** [comment]
> Yup! Did anyone agree on the 2nd of April? :)

Yes, let's do it then! I will follow up with a doodle to have a coordination call sometime next week :) Thanks for your help @gperriard

**Comment by MichaelKohler** [comment]
Closing this, will open a new one for the content and logistics.
