### ISSUE TITLE
Firefox hackathon: Set a date

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/participation#24]
## Goal:

Agree on a date for a Firefox hackathon in Zurich.
## Success:

Have set a date for the hackathon within the next 2 weeks.
## Related Issues & Links:

[meta] #23 
## Roles:

Owner: @MichaelKohler
Involved: @colinfrei @freaktechnik @gion-andri @DocZweirad @grrd01 @J0WI

**Comment by MichaelKohler** [comment]
The italians would support us here, for them it would work on the 9th of April. What do you all think?

**Comment by J0WI** [comment]
I planned anyway to do a talk about Security/Privacy in Firefox/Tor in March. I could do something similar in Zurich.

Topics I thought about are:
- Polaris (Tracking Protection, Mozilla and Torproject relations)
 - Tor itself
- User side
 - Add-Ons, Built-in features
- Admin side
 - CSP
 - TLS

**Comment by colinfrei** [comment]
temp. booked the Liip arena on the 9th.

**Comment by Mte90** [comment]
We are available for our participations but we have to define another date.
As example I am busy with a WordCamp in Turin in that day.
I mention the other italian mozillians interested: @nicokant94 @aroblu94 @ltedone @predorock

**Comment by MichaelKohler** [comment]
Sorry for the misunderstanding, I thought we decided on the 9th. How about the 30th?

**Comment by Mte90** [comment]
For that day I am available but I prefer to wait the other italian volunteers.

**Comment by Mte90** [comment]
I chat with the others for us the 30th is perfect. The problem is that respect to fosdem not all of the Italian mozillians are available.
Actually I am the only one available and I am waiting the confirm of 2 person.
If you confirm the date I book the train/bus the next week and search for bnb/hotels.

**Comment by MichaelKohler** [comment]
Since @Mte90 and @freaktechnik would be available on April 30th, let's move it back to then, like that we don't have that much stress at the beginning of the month organizing two hackathons. Do you agree?

**Comment by MichaelKohler** [comment]
also @colinfrei could you reserve the Arena for the 30th please?

**Comment by colinfrei** [comment]
Reserved.

**Comment by Mte90** [comment]
So the 30th is confirmed? I will buy the ticket for the train and organize for the nights if confirmed.

**Comment by Mte90** [comment]
the date is confirmed?

**Comment by MichaelKohler** [comment]
Yes, I'll open a new issue to coordinate the content and logistics for this.
