### ISSUE TITLE
Organize the March monthly Meetup in Zurich

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/participation#25]
## Goal:

Have a topic and date for the monthly meetup in Zurich.
## Roles:

Owner: @MichaelKohler
Involved: @gion-andri @freaktechnik @colinfrei @DocZweirad @grrd01 @J0WI

**Comment by MichaelKohler** [comment]
maybe @J0WI would like to talk about privacy and encryption since we just have started the campaign around that? (https://advocacy.mozilla.org/encrypt/)

**Comment by freaktechnik** [comment]
I would also like to point out that at the community meeting several people raised interest in a talk about Let's Encrypt, which I would assume also involves some basic how-to-encrypt stuff.

The full list we created was:
- Let's Encrypt
- Web Standards
- Mozilla Clubs (Romandie)
- Open Badges if we find out how to actually issue badges
- New technologies in Dev Edition
- Use WebRTC as alternative to Skype etc...

**Comment by MichaelKohler** [comment]
Ah right, let's include let's encrypt as well there. 

For Web Standards I would go for April, since we need to figure out if Anne has time to do a talk some time.

**Comment by freaktechnik** [comment]
I assume the comment from @J0WI in #24 was meant for here:

> I planned anyway to do a talk about Security/Privacy in Firefox/Tor in March. I could do something similar in Zurich.
> 
> Topics I thought about are:
> -  Polaris (Tracking Protection, Mozilla and Torproject relations)
>   - Tor itself
> - User side
>   - Add-Ons, Built-in features
> - Admin side
>   - CSP
>   - TLS

**Comment by J0WI** [comment]
Oops^^

**Comment by MichaelKohler** [comment]
@J0WI would the 8th or 22nd of March work for you?

Also, where else would you give this talk? Would you need some stickers for that?

**Comment by J0WI** [comment]
I think the 8th is to early, let me check for the 22nd.

Talk is planned for a Cryptoparty in BS. Stickers are always great, but I think I have some.

**Comment by MichaelKohler** [comment]
@J0WI could you also write a title and a small description so I could put that up on meetup.com once we have a date? :)

**Comment by J0WI** [comment]
22nd seems okay.
I'll try to work on it this weekend.

**Comment by MichaelKohler** [comment]
@J0WI quick ping here, do we want to do this on the 22nd? If so, we can ask @colinfrei to reserve the Arena :)

**Comment by J0WI** [comment]
Yes, confirm the 22nd.
Sadly I haven't started working on it yet, but feel free to choose a provisional title.

**Comment by J0WI** [comment]
I think I'll not focus on Tor and TLS too much, they are worth a own talk.

**Comment by MichaelKohler** [comment]
Hey @J0WI, I'd like to announce the meetup within the next days, do you think you could come up with a title and a few sentences about the content? 2-3 would be enough and we could still change it :)

**Comment by MichaelKohler** [comment]
Meetup event: http://www.meetup.com/Mozilla-Meetup-Switzerland/events/229533338/
@colinfrei could you please reserve the 22nd at 19:00? thanks!

I will announce the event once the location is reserved.

**Comment by colinfrei** [comment]
Reserved.

**Comment by MichaelKohler** [comment]
Thanks, Colin. Meetup is announced, Event pages are up to date.

@J0WI if you want me to change the description, just tell me. I think we're ready for that, so I'm closing this one :)

Thanks for all your help!
