### ISSUE TITLE
Organize the April monthly meetup in Luzern

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/participation#26]
## Goal:

Have a date and speaker for the monthly meetup in Zurich.
## Success:

We have planned everything for the meetup.
## Roles:

Owner: @MichaelKohler
Involved: everyone

**Comment by MichaelKohler** [comment]
@annevk would you like to have a talk sometime in April during the week in Zurich? We would love to hear about Open Standards :)

**Comment by annevk** [comment]
Would love to, but getting to Zurich takes two hours and getting back takes another two (and has to be done way before midnight due to public transport schedules). Luzern would probably work, but then everyone else probably has to travel too much.

**Comment by MichaelKohler** [comment]
Thanks for your answer, @annevk . We could probably get a location in Luzern. This would also enable us to reach out to people that have never been in touch with us, this is a great opportunity. Regarding traveling, we're fine with that.

Anne, could you propose a few dates that would fit you so I could reach out regarding the location? Thanks!

**Comment by annevk** [comment]
Apart from the first week and Fridays I think I'm generally available throughout April. Weekends would be slightly easier, but during the week is fine too.

**Comment by MichaelKohler** [comment]
Reached out to Netnode, let's see if they are willing to host us and could give us a few dates that would work for them :)

**Comment by MichaelKohler** [comment]
> Apart from the first week and Fridays I think I'm generally available throughout April. Weekends would be slightly easier, but during the week is fine too.

@annevk how about April 13 or April 27? If so, what time would be best for you? :)

**Comment by annevk** [comment]
I prefer April 13. There's a small chance something else might come up, but I should know that relatively shortly. If I take the train at 7PM here I should be able to show up before 8:30PM in most places in Luzern. Would that work?

**Comment by MichaelKohler** [comment]
Perfect, we will meet on April 13th, 19:00 at Netnode. They haven't fully confirmed yet, but that should be okay.

Preliminary agenda:

19:00 - 19:15 Introduction to Mozilla & What are we currently doing with Connected Devices?
19:15 - 20:00 Hacking on Firefox with JavaScript
20:00 Open Standards (Anne)

I will create a meetup.com event for it once confirmed.

**Comment by MichaelKohler** [comment]
It's confirmed, we start at 19:00 with Welcome drinks and then I'll give an introduction to Mozilla at 19:30. Here's the meetup page: http://www.meetup.com/TechUP-Luzern/events/229099309/ (we'll leave the firefox hacking part in that case).

I will create the same for the Mozilla Switzerland meetup as well. Will also update the Reps page.

**Comment by MichaelKohler** [comment]
https://reps.mozilla.org/e/open-web-standards/
http://www.meetup.com/TechUP-Luzern/events/229099309/
http://www.meetup.com/Mozilla-Meetup-Switzerland/events/229635108/

I think we have everything we need for it, closing this one :) Thanks for all your help!
