### ISSUE TITLE
Organize a followup meetup in Lausanne after the hackathon

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/participation#27]
## Goal:

Organize a followup meetup in Lausanne to have a ground base for future events.
## Success:

We have at least 7 people at the meetup and engaged in discussions after the talk.
## Roles:

Owner: @MichaelKohler
Involved: @gperriard, @juliandescottes
## Required:
- [ ] Set the date (needs to be after the hackathon) (all, small, Due: 23.05.2016) 
- [ ] Secure the location (@gperriard, medium, Due: 27.05.2016) 
- [ ] Promote on meetup.com and other channels (@MichaelKohler, medium, Due: 01.06.2016)

**Comment by MichaelKohler** [comment]
I'd recommend to have a followup during another meetup we could organize with a talk. What kind of talks could be interesting? I think something around Firefox would be good. Some ideas:
- Firefox Dev Tools
- WebExtensions

@freaktechnik @gperriard  any other ideas?

**Comment by MichaelKohler** [comment]
Updated metrics: I've deleted the requirement for "hackathon people", since we first need to have a base that are actually interested in Mozilla.

**Comment by MichaelKohler** [comment]
@gperriard hi Geoffroy, could you please check with Liip if we could run an evening meetup in the week of May 23rd? Thank you!

**Comment by MichaelKohler** [comment]
I'd prepare a talk about Dev Tools to speak there

**Comment by gperriard** [comment]
@MichaelKohler unfortunately, I won't be here this week. Would it be possible to postpone it to the 31th May? So it'll be easier for me to organize something in Liip offices.

**Comment by MichaelKohler** [comment]
@gperriard sure! Thanks for your help.

@juliandescottes would that week work for you as well?

**Comment by juliandescottes** [comment]
Sorry my schedule has been shifting a lot these days. I'm not sure I will be in the Lausanne area around the end of May. Sorry about this.

If I happen to be around I'll let you know but chances seem pretty low.

**Comment by gperriard** [comment]
@MichaelKohler the room is available for the 31th May if needed.

**Comment by MichaelKohler** [comment]
I'll know shortl if May 31st will work for me, maybe I won't be able to do that one. Will report back. Thanks for checking!

**Comment by MichaelKohler** [comment]
@gperriard Unfortunately I won't make it then :(

Alternate dates: 8.6./ 9.6. / or the week of 20.06. .. could you please check for those? :)

**Comment by MichaelKohler** [comment]
Let's talk about our strategy for the Romandie tonight and then we will open new issues.
