### ISSUE TITLE
Organize topics and logistics for IoT hackathon in Lausanne

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/participation#28]
## Goal:

Organize everything for the IoT hackathon in Lausanne on April 2nd, so we can start promoting it.
## Success:

We have a plan on content, logistics and promotion.
## Related Issues & Links:

[meta] #12 
## Roles:

Owner: @MichaelKohler
Involved: @gperriard @loleg @colinfrei @freaktechnik 
## Required:
- [x] Schedule a call to discuss content and logistics (@MichaelKohler, [medium], Due: March 7th)
- [x] Have finalized location and logistics (@MichaelKohler, [medium], Due: March 13th)
- [x] Have a plan on how to promote this hackathon (@MichaelKohler, [medium], Due: March 15th)

**Comment by gperriard** [comment]
Yop! Regarding the discussion, would this Thursday 10th March be fine for everyone?
@MichaelKohler

**Comment by freaktechnik** [comment]
I can take part on march 10th if we get our fiber connection by then.

**Comment by loleg** [comment]
I must say, I love this idea. Please let me save you the trouble of
organising a high quality event in less than a month: consider instead
joining the Energy Hackdays on the weekend of April 8 - 9, on a closely
linked topic, at two amazing locations, with great support and a bunch of
good people signed up!

Come on Mozillians, bring your sensors and open devices, and lets hack them
for the good of the planet. Details at http://make.opendata.ch/energy

**Comment by MichaelKohler** [comment]
> Yop! Regarding the discussion, would this Thursday 10th March be fine for everyone?
> @MichaelKohler

Sounds good to me, but I won't be available after 16:00 until around midnight. Would Wednesday evening work?

**Comment by MichaelKohler** [comment]
> I must say, I love this idea. Please let me save you the trouble of organising a high quality event in less than a month: consider instead joining the Energy Hackdays on the weekend of April 8 - 9, on a closely linked topic, at two amazing locations, with great support and a bunch of good people signed up!

To be honest, we're not aiming for a "big" hackathon. I think it's already a success if we have 10 people. We'll keep the logistics part to a minimum, therefore this should work.

> Come on Mozillians, bring your sensors and open devices, and lets hack them for the good of the planet. Details at http://make.opendata.ch/energy

I think most of us won't be available on Friday, so only Saturday would work. This would be a nice way to get into the energy topic. For myself, I'll definitely think about it :)

**Comment by gperriard** [comment]
@MichaelKohler arf .. I didn't see your message.
Unfortunately, I can't make it earlier today. Would next Tuesday at 19:00 be fine for you?
What about the others?

**Comment by MichaelKohler** [comment]
@gperriard no worries, yes that would work. 

Preliminary agenda:
- Confirm location
- Agenda
- Content
- Hardware
- Lunch
- Follow-up after the hackathon
- Next steps

**Comment by MichaelKohler** [comment]
@gperriard would today at 19:00 still be okay with you? if so, let's do this and discuss at least the next steps :) we did our last planning meeting in Vidyo, but that doesn't work that well depending on your OS. Want to use skype?

**Comment by gperriard** [comment]
@MichaelKohler due to unforeseen circumstances, I'm won't be able to join you tonight for the video conf.
Don't wait on me for this call, however I would be available next Tuesday at 19:00 if ever.
Sorry for the inconvenience.

**Comment by MichaelKohler** [comment]
I've started a brainstorm etherpad here: https://public.etherpad-mozilla.org/p/mozillach-iot-hackathon-april2

The currently open questions are mostly around the content.

@gperriard could you please confirm that the proposed agenda would work for Liip (e.g. confirming the loation)? Also could you answer the open question regarding lunch?

**Comment by gperriard** [comment]
@MichaelKohler That should normally be fine with the location. I already got a ok few weeks ago.
I'll check tomorrow with someone from Lausanne about the lunch and everything related to the office (key for the door, etc.)

**Comment by gperriard** [comment]
Regarding the hardware devices, I think it would be risky to rely only on people bringing their devices.
@colinfrei do you know if we have some kind of IoT hardware at Liip that we could borrow? (raspery pi, ...)

**Comment by MichaelKohler** [comment]
> Regarding the hardware devices, I think it would be risky to rely only on people bringing their devices.

Definitely, I've added what I can bring in terms of hardware on the Etherpad.

**Comment by colinfrei** [comment]
there might be some stuff lying around, I guess it depends on what we're actually looking for. I can check with Michael tomorrow.

**Comment by MichaelKohler** [comment]
> there might be some stuff lying around, I guess it depends on what we're actually looking for. I can check with Michael tomorrow.

Please check with @freaktechnik since I won't be able to attend tomorrow :(

**Comment by gperriard** [comment]
Hoi!

Here are some info about the location and the lunch.

**Location**
I confirm that the hackday can be held at **Liip office, rue Etraz 4, 1003 Lausanne**
We have a room, a kitchen and a terrace at our disposal with the following furnitures:
- 1x beamer
- tables and chairs
- 1x sofa
- wifi
- electric connections
- ping-pong table :)

The office will be for us from 08:00 to 19:00.
The main entrance is closed during weekend, therefore we will have to go opening the door when people are coming. Usually, I tell people to tweet or call me, then we can open the doors.

Let me know, if you see something more you would need.

**Lunch**
We have three solution:
1. Going to [cafe St-Pierre](http://www.cafesaintpierre.ch/), it's 2 min. from the office but we need to book a table asap
2. Ordering pizza.
3. Let people go grab something in the neighbourhood

**Open points**
- Did you plan having beverages for attendees?
- @MichaelKohler do you already have a meetup link or something that I can share to gather people?

**Comment by MichaelKohler** [comment]
> Did you plan having beverages for attendees?

That would be good. We can bring some drinks from the supermarket when we arrive (we don't really have a budget for this event).

> do you already have a meetup link or something that I can share to gather people?

Just created, here we go: http://www.meetup.com/Mozilla-Meetup-Romandie/events/229797456/ . Would be great if you could spread that around :)

**Comment by MichaelKohler** [comment]
Looks like we're all set for tomorrow. Let's see if people show up, otherwise we can talk on how we can improve and maybe work on our own little project :)
