### ISSUE TITLE
Speaker Documentation

### ISSUE THREAD

**Issue by freaktechnik** [mozillach/participation#32]
## Goal:

Document infrastructure and procedure for speaking at a mozilla.ch event.
## Success:

Speakers have a comprehensive idea of what they will find at the location.
## Roles:

Owner: @freaktechnik
Involved: @MichaelKohler 
## Required:
- [x] Initial documentation on Switzerland/Events on WIMO (@freaktechnik, medium, Due: 20.04.2016) 
- [x] Add Romandie specific info (@MichaelKohler, medium, Due: 30.04.2016)
- [x] Add "Event organization" topics (@MichaelKohler, medium, Due: 30.04.2016)
- [x] Feedback by other speakers (@grrd @J0WI , @colin, small, Due: 30.05.2016)

**Comment by freaktechnik** [comment]
Page started on https://wiki.mozilla.org/Switzerland/Events

**Comment by MichaelKohler** [comment]
I've added the "Organizing an event" section and the Lausanne specific stuff.

https://wiki.mozilla.org/Switzerland/Events

I think we're ready for review, could @J0WI @grrd01 @colinfrei have a look and give some feedback if this is everything we need to think of? Thank you!

**Comment by J0WI** [comment]
We also have some tables and sometimes beverages in Zurich.
AFAIK there is also a tabletop soccer and various adapters for the HDMI plug.

A little description how to get there would be nice (e.g. bus/next tram station, which line number from railway station) or time by foot.

**Comment by freaktechnik** [comment]
I think in the arena at liip Zürich there is only a HDMI -> mini Displayport adapter. I'm not sure that's something that we should explicitly list and instead if someone asks if we have one, say that there should be one around.

> A little description how to get there would be nice (e.g. bus/next tram station, which line number from railway station) or time by foot.

Good idea.

**Comment by MichaelKohler** [comment]
I've edited the page according to Gerard's feedback (at least the parts that weren't added yet). @freaktechnik I guess we're ready to close this issue, right?

**Comment by freaktechnik** [comment]
I'd assume so, the basic goal is met in my opinion.

**Comment by MichaelKohler** [comment]
Since it's a wiki page, we can always edit it if we see that something is missing or not clear :)
