### ISSUE TITLE
Start discussions on Discourse

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/participation#34]
## Goal:

We know whether we can move to Discourse without subjections or not.
## Roles:

Owner: @MichaelKohler
Involved: @freaktechnik 
## Required:
- [x] Start discussion on Mailing list (no objection == let's move ahead) (@MichaelKohler, medium, Due: 30.04.2016)
- [x] Create Switzerland subcategory on Discourse (@MichaelKohler, medium, Due: 20.05.2016)
- [x] Deprecate Mailing list and send out tutorial on how to switch (@MichaelKohler, medium, Due: 01.06.2016)

**Comment by MichaelKohler** [comment]
added a more realistic timeline

**Comment by MichaelKohler** [comment]
sent out a mail to the mailing list, open for feedback until May 10

**Comment by MichaelKohler** [comment]
I guess we can continue here since we didn't have any objections (or any feedback at all for that matter). I'll request a new discourse category for us.

**Comment by MichaelKohler** [comment]
Discourse request is here: https://bugzilla.mozilla.org/show_bug.cgi?id=1274239

**Comment by freaktechnik** [comment]
https://discourse.mozilla-community.org/c/communities/switzerland

**Comment by MichaelKohler** [comment]
I guess we can close this one. I think it's best to just not post any updates to the mailing list after June. I'll still be subscribed to have people redirected to Discourse if necessary.
