### ISSUE TITLE
Get in touch with all unvouched Mozillians

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/participation#35]
## Goal:

We have contacted and checked for possible interest with all unvouched Mozillians that have registered some time in the past.
## Roles:

Owner: @MichaelKohler
Involved: @freaktechnik 
## Required:
- [x] Draft an email to be sent out (@MichaelKohler, medium, Due: 26.03.2016)
- [x] Send out the mails (@MichaelKohler, medium, Due: 28.03.2016)
- [x] Onboard interested persons (@MichaelKohler, medium, Due: 16.04.2016)

**Comment by freaktechnik** [comment]
Moving to next Q. Feel free to close this if you feel it is no longer relevant.

**Comment by MichaelKohler** [comment]
@freaktechnik I still think this is highly relevant. Let's get in touch with them after we have decided on the next meetup/hackathon and invite them!

**Comment by MichaelKohler** [comment]
I will do this with an invite to our next meetup.

**Comment by MichaelKohler** [comment]
Will be done for #49

**Comment by MichaelKohler** [comment]
Unfortunately I still haven't had time to do this. I now have collected all email addresses from mozillians.org, and I've marked spam accounts. I will try to send out the emails tomorrow, but it might be too late for tomorrow's event. However I will include a link to the communication channels and Meetup/Twitter specifically.

**Comment by MichaelKohler** [comment]
Done
