### ISSUE TITLE
Organize May meetup

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/participation#39]
## Goal:

Have a meetup in Zurich for May.
## Success:

At least 10 people show up to a meetup in Zurich in May.
## Related Issues & Links:

[goal] #7 
## Roles:

Owner: @MichaelKohler
Involved: @freaktechnik , @colinfrei 
## Required:
- [x] Find a topic and speaker (@MichaelKohler, medium, Due: 03.05.2016) 
- [x] Find a date (???, medium, Due: 03.05.2016) 
- [x] Promote meetup (???, medium, Due: 10.05.2016)

**Comment by MichaelKohler** [comment]
Any idea for a topic we could have a talk about?

**Comment by MichaelKohler** [comment]
Reached out to Mark Shillitoe to ask if he wants to do a talk about Webmaker

**Comment by MichaelKohler** [comment]
Mark could do May 18th, he will confirm next week. He would be talking about Webmaker.

@colinfrei could you please reserve the Arena on May 18th, 19:00 for us? Thanks!

@freaktechnik should we create the event even though it's not yet fully confirmed? (at least on Reps?)

**Comment by colinfrei** [comment]
reserved

**Comment by freaktechnik** [comment]
@MichaelKohler I think creating it on reps should be okay, I wouldn't create the meetup event yet and trigger the notifications to the audience yet...

**Comment by freaktechnik** [comment]
confirmed: https://twitter.com/markshillitoe/status/727576827737350144
