### ISSUE TITLE
Get added to freie-termine.ch

### ISSUE THREAD

**Issue by freaktechnik** [mozillach/participation#40]
## Goal:

Our events are on freie-termine.ch 
## Roles:

Owner: @freaktechnik
Involved: @MichaelKohler, whoever else wants to join the conversation.
## Required:
- [x] Define which calendar to use (@freaktechnik, @MichaelKohler, small, Due 31.05.2016)
- [x] Contact freie-termine.ch (@freaktechnik, small, Due: 30.06.2016)

**Comment by freaktechnik** [comment]
We should decide which calendar feed we'd ask to be included. We have two options, as far as I know:
- Reps (same as we have on the website), would include informal events
- Meetup , would not include informal events

**Comment by freaktechnik** [comment]
Kind of off-topic, but I sent an e-mail to ask to be added to http://www.lugs.ch/lugs/termine/. Still haven't found a contact for freie-termine.ch.
EDIT: getting added to the lugs list would also add us to freie-termine.

**Comment by MichaelKohler** [comment]
I've sent you a contact in private

**Comment by freaktechnik** [comment]
By submitting our dates to LUGS we will also appear on freie-termine.ch
