### ISSUE TITLE
Custom URL shortener

### ISSUE THREAD

**Issue by freaktechnik** [mozillach/participation#41]
## Goal:

A custom URL shortener where we have full control over all the generated URLs and can change targets if we want to.
## Success:

We have a working URL shortener on a subdomain of mozilla.ch
## Related Issues & Links:

(none yet)
## Roles:

Owner: @freaktechnik
Involved: @MichaelKohler 
## Required:
- [x] Investigate URL self-hosted shorteners (@freaktechnik, small, Due: 30.05.2016)
- [ ] Get working container up on paas (@owner, medium, Due: 30:05.2016)
- [ ] Request the DNS record (@owner, small, Due: 30.06.2016)

**Comment by freaktechnik** [comment]
I'd suggest to use http://yourls.org/. We'll need to set up a container that we can configure for our usage and get a database container, too.

**Comment by J0WI** [comment]
I don't understand the need of short URLs, but can we at least ask for mzl.la before we create set up something new?

**Comment by freaktechnik** [comment]
mzl.la can already be used via bit.ly links but only for mozilla.org urls (not sure if the newer .community and etherpad-mozilla.org are included). Reason is mostly that handing out URLs to people at hackathons is not that easy with complicated URLs that tend to happen.

Oh, and another criteria was to have the short URLs to be editable, so we can re-use simple things like "/feedback".

**Comment by MichaelKohler** [comment]
mozilla.community, mozilla-community.org and etherpad-mozilla.org are not included there AFAIK. And also we would want to have nice URLs like /feedback, /firefox, /mailinglist, whatever.

For mzl.la we need would need access to it, and then we would still depend on not-already-used shortnames. Further I have no idea how bit.ly is handling this on their side, so extending this to "mozilla-related" domains might be too hard.

**Comment by freaktechnik** [comment]
Moving to next Q.

**Comment by MichaelKohler** [comment]
Do you still want this to happen? I think we can focus on more important things this semester. We can either close it or move it back to the backlog.
