### ISSUE TITLE
Organize Half-year Community Meetup

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/participation#42]
## Goal:

We have organized a community meetup to share information from the All Hands and define our activities and goals for the second half of the year.
## Roles:

Owner: @MichaelKohler
Involved: @freaktechnik 
## Required:
- [x] Send out doodle for dates (@MichaelKohler, small, Due: 20.05.2016) 
- [x] Decide on a date (@MichaelKohler, small, Due: 27.05.2016) 
- [x] Ask Colin to reserve a meeting room or the Arena or reserve a space in Bern depending on the attendees (@MichaelKohler, medium, Due: 28.05.2016) 
- [x] Create preliminary agenda (@MichaelKohler, medium, Due: 30.05.2016)
- [x] Review agenda (@freaktechnik, medium, Due: 03.06.2016)
- [x] Add London All Hands Information to Agenda (@freaktechnik / @MichaelKohler, medium, Due: 20.06.2016)

**Comment by MichaelKohler** [comment]
Doodle here: http://doodle.com/poll/xk756dkrub8x3rtd

Mail sent out to the Mailing list

**Comment by MichaelKohler** [comment]
Pinging some people to make sure that they see it and fill out the doodle :) @gperriard @annevk @juliandescottes

**Comment by annevk** [comment]
That'll be hard for me to attend, but let's try to get together in London!

**Comment by MichaelKohler** [comment]
@colinfrei could you please fill out the doodle as well? (one for you and one for having space, either arena or a meeting room)

@DocZweirad maybe you could fill it out as well? :)

**Comment by colinfrei** [comment]
Done. I filled in Arena, meeting room will always work, though much easier if I'm there.

Bern office might also be possible. Let me know if necessary, and I can look into it.

**Comment by MichaelKohler** [comment]
Let's do it on the 20th. @colinfrei could you please reserve the space? (Arena or meeting room, doesn't really matter)

**Comment by colinfrei** [comment]
reserved.

**Comment by MichaelKohler** [comment]
Agenda: https://public.etherpad-mozilla.org/p/mozillach-community-meetup-june2016
Reps event: https://reps.mozilla.org/e/mozilla-switzerland-community-meetup-1/

Please feel free to comment on the agenda, this is a rough draft.
