### ISSUE TITLE
Organize talk in Zurich in September

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/participation#43]
## Goal:

We have at least one talk organized in Zurich in September to finish our summer break.
## Roles:

Owner: @MichaelKohler
Involved: @freaktechnik 
## Required:
- [x] Decide on a date (@MichaelKohler, Due: 11.08.2016) 
- [x] Come up with the topic and write a description (@freaktechnik, Due: 15.08.2016) 
- [x] Reserve the location (@MichaelKohler, Due: 18.08.2016) 
- [x] Announce on meetup/techup/twitter/discourse (@MichaelKohler, Due: 21.08.2016)

**Comment by MichaelKohler** [comment]
As previously discussed with @freaktechnik a talk about WebExtensions would be nice. We came up with the 19th of September, if that works for the Arena.

@freaktechnik could you please post your abstract here?
@colinfrei could you please reserve the Arena for the 19th of September at 19:00? (additionally to the currently existing reservation ;))

Thanks!

**Comment by freaktechnik** [comment]
> Firefox is drastically changing its extension system and replacing it with the Chrome-like WebExtensions. Chrome-like is an empty description for you? Perfect, Martin will explain what WebExtensions are, why you should care about them and what to do if you have an extension for Firefox that you will have to port over.

I wonder if I should add an engagement sentence for people that have written chrome extensions and are interested in what porting involves.

**Comment by MichaelKohler** [comment]
Yes, please :)

**Comment by colinfrei** [comment]
Reserved the 19th.

**Comment by MichaelKohler** [comment]
Merci!

**Comment by freaktechnik** [comment]
> Firefox is drastically changing its extension system and replacing it with the Chrome-like WebExtensions. Chrome-like is an empty description for you? Perfect, Martin will explain what WebExtensions are, why you should care about them and what to do if you have an extension for Firefox that you will have to port over. For those already familiar with the Chrome extension API, the talk will point out the differences and nuances to check when porting.

**Comment by MichaelKohler** [comment]
Added to meetup and announced on Discourse:

http://www.meetup.com/Mozilla-Meetup-Switzerland/events/233444437/
https://discourse.mozilla-community.org/t/introduction-to-webextensions/10350

Tweet will go out shortly as well.
