### ISSUE TITLE
Better Twitter curation

### ISSUE THREAD

**Issue by freaktechnik** [mozillach/participation#46]
## Goal:

Create a much easier contribution opportunity for content for people that don't have direct access to the Twitter account.
## Success:

We have a stable system to schedule tweets and assign work to multiple persons and produce a consistent flow of content on our Twitter account (@MozillaCH).
## Related Issues & Links:

Initiative for #44 
## Roles:

Owner: @freaktechnik
Involved: @MichaelKohler 
## Required:
- [x] Finalize [board](https://trello.com/b/MhHQZ1uF/mozilla-ch-twitter-content-example) (@freaktechnik, [small], Due: 01.11.2016) 
- [x] Create automated content feed for GitHub (@freaktechnik, [medium], Due: 15.02.2017)
- [x] Finalize parameters for content feed automation (@freaktechnik, [medium], Due: 15.02.2017)
- [x] Document process on wiki.mozilla.org (@freaktechnik [medium], Due: 1.03.2017)

**Comment by freaktechnik** [comment]
The Trello board linked above is my suggested solution for the problem described in [the discourse thread](http://discourse.mozilla-community.org/t/better-twitter-curation/10721/2).

The "Needs Reaction", "Events" and "Tweeted" columns would be filled automatically and would only require action to finalize content, if it's not in "Tweeted". We could additionally automate actually tweeting from the "To Tweet" column, which would essentially make the Trello board a collaborative Twitter scheduler, where everyone with access to the board can Tweet with the mozillaCH account. Tweets would make their way from left to right and generally follow a description format like:

``` md
## Meta content information
Description and information useful for writing the actual tweet content

## Tweet Content
Text content of the tweet that should be sent out.

## Retweet
Link to tweet if a tweet should be retweeted.
```

**Comment by freaktechnik** [comment]
On the automation tool: this will probably be a node based tool, which I'll create a repo on here. Not sure yet where it would run, but in case of doubt it would be easy enough to run it on heroku and just make it run once or twice a day.

**Comment by MichaelKohler** [comment]
I completely love and agree with your general data structure. However, since the GitHub projects API is not preview anymore and can be used (not tested though), maybe we could even use that? https://developer.github.com/v3/repos/projects/

I'm not sure how many people would contribute through trello vs. through GitHub, but since there is a lot of stuff going on nowadays on GitHub, I think we'd be fine. One drawback would be that as far as I know you still need to manually add issues to the project board. But I guess we could automate that to automatically add a new card when a new issue is created in the repository.

What do you think?

**Comment by freaktechnik** [comment]
I would think the potential of people willing to contribute to tweets having github is far greater, since we also have the whole participation planning via github.

**Comment by freaktechnik** [comment]
Development of the content bridge will happen in https://github.com/mozillach/gh-projects-content-queue
Design decisions about what kind of stuff it should do will happen in there.

**Comment by freaktechnik** [comment]
As content queue is ready for general usage, I've started to draft documentation. Instead of making it an article on the wiki, I decided it may be better to put it in a CONTRIBUTING.md in the queue repo. I've created a draft as gist: https://gist.github.com/freaktechnik/aa029f23fc7d711b75792512bdb31588

**Comment by freaktechnik** [comment]
This is essentially done. All that has to be done is to add some references to this system on the wiki and note this in the discourse thread.

**Comment by freaktechnik** [comment]
All done!
