### ISSUE TITLE
Organize March Talk

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/participation#49]
## Goal: 
Our March talk is organized.

## Roles:
Owner: @MichaelKohler
Involved: @freaktechnik, @colinfrei 

## Required: 
- [x] Decide on topic from our backlog and find speaker (@MichaelKohler, Due: 02.03.2016) 
- [ ] Decide on date and reserve location (@MichaelKohler, Due: 08.03.2016)

**Comment by itsN1X** [comment]
Hope to see #35 checkout for me in near future : )
