### ISSUE TITLE
Organize WebVR Hackathon in July

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/participation#53]
## Goal: 
WebVR hackathon in Lausanne is organized.

## Related Issues & Links: 
https://discourse.mozilla-community.org/t/webvr-workshop-in-lausanne/15500/4

## Roles:
Owner: @MichaelKohler
Involved: @freaktechnik @gperriard @colinfrei @AlexLakatos

## Required: 
- [x] Draft of the agenda (@MichaelKohler, Due: 20.05.2016) 
- [x] Announce on Meetup Lausanne (@MichaelKohler, Due: 20.05.2016) 
- [x] Finalize agenda (@MichaelKohler, Due: 30.05.2016) 
- [x] Organize drinks (maybe Liip? ;)) (@gperriard, Due: 30.05.2016) 
- [x] File budget request for logistic expenses (Cardboards?) (@MichaelKohler, Due: 30.05.2016) 
- [x] Promote through all channels (@MichaelKohler/@gperriard, Due: 15.06.2016) 
- [x] Do a second promotion round (@MichaelKohler, Due: 30.06.2016) 
- [x] Prepare Intro to VR session (@MichaelKohler/@AlexLakatos, Due: 15.07.2016)
- [ ] Send reminder to full group again (@MichaelKohler, Due: 15.07.2016) 
- [x] Organize VR setup from ZH office (@MichaelKohler, Due: 20.07.2016) 
- [ ] Organize Flyers we can put up so people find us (@MichaelKohler, Due: 22.07.2016)

**Comment by MichaelKohler** [comment]
Meetup Lausanne event page: https://www.meetup.com/Mozilla-Meetup-Romandie/events/239994710/ (not yet announced)

**Comment by AVGP** [comment]
Happy to help! I can bring Cardboards and help with workshops or talks. 

You mentioned you wanted some intro beyond A-frame and I'm happy to explain the spec or whatever needs explaining =)

**Comment by gperriard** [comment]
Hello! Good news, Liip is going to sponsor the drinks and croissants. :)

Regarding the agenda, would it be possible to start at 10 instead of 11:30 that would allow us to have some time to welcome people and have more time for hacking.

I would propose the following agenda:
10:00 - 10:30 Welcome
10:30 - 11:00 Intro to WebVR / A-Frame
11:00 - 11:45 Demos with a VR device / Thinking about what you want to create
11:45 - 17:00 Hacking on your ideas
17:00 - 18:00 Presenting your demos/creations if you want to
18:00 - 20:00 Drinks and snacks

I would restrain the number of participants to 20 people so we are have enough space, tables and chairs to hack.

What do you think?

@AVGP +1 for an overview of the spec.

**Comment by MichaelKohler** [comment]
> Happy to help! I can bring Cardboards and help with workshops or talks.

This would be great! How many cardboards do you have? I can bring one as well. Maybe we don't even need to buy some in that case.

> Good news, Liip is going to sponsor the drinks and croissants. :)

Yay, thanks!

> Regarding the agenda, would it be possible to start at 10 instead of 11:30 that would allow us to have some time to welcome people and have more time for hacking.

Do you think people will show up that early on a Saturday? ;) I like the idea of having enough time to hack, as long as we actually have people attending :)

**Comment by AVGP** [comment]
@MichaelKohler I have at least ten, but I gonna check how much exactly I've got available. Seeing as we limit to 20 people (right?) I can see if I can bring one for all attendees.

**Comment by MichaelKohler** [comment]
@AVGP I think I'll go for 25 or even 30 (including organizers and speakers/helpers), as I'm pretty sure not everybody will show up. In any case, 10 are enough, people can share :)

**Comment by gperriard** [comment]
> Do you think people will show up that early on a Saturday? ;) I like the idea of having enough time to hack, as long as we actually have people attending :)

I think 10 is okay. People can still join later if they want to.
Is it an issue for you? Can I update the meetup with the agenda I proposed?
I plan to be at the office around 08h30 to prepare the room.

We could also have a Hololens for demo. Shall I bring it?

**Comment by MichaelKohler** [comment]
OK, I've changed the agenda and announced it:

https://www.meetup.com/Mozilla-Meetup-Romandie/events/239994710/
https://www.meetup.com/Mozilla-Meetup-Switzerland/events/240560784/

> We could also have a Hololens for demo. Shall I bring it?

I honestly don't know the status of Hololens and WebVR, maybe @AVGP does. If it works, I'd be definitely happy to have one :)

**Comment by gperriard** [comment]
Thx @MichaelKohler !
I'll announce it today. I can't wait until this hackday!

Regarding the Hololens, I'll try to bring it. Maybe we will use it maybe not but I think it's always good to have related VR device around so people get a better overview about what's on the market.

**Comment by gperriard** [comment]
Btw, I also posted the meetup on techup.ch 
http://techup.ch/2527/mozilla-webvr-a-frame-hackathon

**Comment by AVGP** [comment]
I just noticed that I won't be in CH when the hackathon takes place, but I can give the cardboards to someone else and then you'll have 'em at the event. 10 enough, yea?

**Comment by MichaelKohler** [comment]
Oh no, I would have loved to have you there. However, yeah, 10 are totally fine and we can organize the pickup.

**Comment by MichaelKohler** [comment]
I think we're ready! Thanks a lot for the help @gperriard!

**Comment by J0WI** [comment]
There are different timetables on Mozilla Reps/mozilla.ch (starting at 11:30 AM) than on Meetup (starting at 10:00 AM).

**Comment by MichaelKohler** [comment]
Thanks,corrected :)

**Comment by gperriard** [comment]
@AVGP, thank you a lot for organising the venue of Ben for the talk on A-Frame in the today Mozilla meetup.
The talk was really well done and inspiring! :)
