### ISSUE TITLE
With talks and events we increase our reach and provide a valuable information source regarding the Open Web

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/participation#7]
## Objective:

With talks and events we increase our reach and provide a valuable information source regarding the Open Web.
## Key Results:
- [x] Have at least 5 physical meetups in the first half of the year in Zurich
- [x] Organize a Hackathon in Lausanne (topic TBD) in the first quarter
- [x] Organize at least 3 meetups In Lausanne apart from the Hackathon to introduce the French-speaking part to Mozilla
- [x] Have at least 3 informal meetups without talks (“get-togethers”)
- [ ] Have one meetup with CH OPEN and/or OpenData.ch to discuss synergie

**Comment by MichaelKohler** [comment]
3 meetups fulfilled, if we also count meetups where we had a talk. So the only thing not achieved here is the CH OPEN meeting.

**Comment by J0WI** [comment]
See also #13
