### ISSUE TITLE
Mozilla Privacy Team Update and further involvement

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/participation#9]
## Goal:

Provide a base of information for the Mozilla Privacy team (Raegan MacDonald). This is the base for any future blog posts or discussions about involvement from their side.
## Success:

The privacy team has all the necessary information regarding NDG and the Swiss voting process.
## Roles:

Owner: @MichaelKohler
Involved: @J0WI 
## Required:
- [x] Document voting process (@MichaelKohler, medium, Due: 07.02.2016) 
- [x] Document all resources for the NDG referendum (EN or FR) (@MichaelKohler, medium, Due: 08.02.2016)
- [x] Find good overview of "critical" paragraphs (@J0WI, medium, Due: 09.02.2016)
- [x] Get in touch with the privacy team and help them draft a first statement (@MichaelKohler, @J0WI ?, medium, Due: 14.02.2016)
- [x] Evaluate next steps (@MichaelKohler, @J0WI ?, medium, Due: 15.03.2016)

**Comment by MichaelKohler** [comment]
I have started an Etherpad here to gather information: https://public.etherpad-mozilla.org/p/mozillach-ndg-info (feel free to add even after I have sent the first version of it to Raegan)

**Comment by J0WI** [comment]
See also https://public.etherpad-mozilla.org/p/mozillach-bupf-ndg-initative

**Comment by MichaelKohler** [comment]
I also added the official proposed law texts.. do we have an overview of critially bad paragraphs on the text? @J0WI

**Comment by MichaelKohler** [comment]
I sent a mail to Raegan (cc Mailinglist).

**Comment by J0WI** [comment]
Digiges collected a bunch of details. Here are some articles with examples of bad paragraphs:
https://www.digitale-gesellschaft.ch/2013/06/09/prism-heisst-in-der-schweiz-kabelaufklarung/
https://www.digitale-gesellschaft.ch/2014/10/26/neues-nachrichtendienstgesetz-ueberwachung-wie-am-flughafen/
https://www.digitale-gesellschaft.ch/2014/03/08/botschaft-zum-neuen-nachrichtendienstgesetz/
https://www.digitale-gesellschaft.ch/2013/08/09/prism-in-der-schweiz-oder-lavabit-als-beispiel-wohin-uns-bupf-und-ndg-fuhren/

You should double check, if something changed in the final draft.

**Comment by MichaelKohler** [comment]
I'm in touch with Raegan, she still has a few questions regarding the voting process. I will update this once these questions have been answered and we know the next steps from the Privacy team's side.

**Comment by MichaelKohler** [comment]
I had a meeting with the Policy team, here are the rudimentary notes:
- In general the organisation stands behind us, the policy team agrees that fighting this is in Mozilla's interest
- Since there are a lot of similar proposals/changes going on, we might not be able to have dedicated support from the team all the time. But we can reach out for help if we see something that we can't handle ourself.
- Maryam will start to compile a list of allies (gave her the resources she needs I hope) and start to draft a blog post (it might have the best impact if we publish after June 5th)
- Raegan has already talked to other organizations involved in Switzerland, she will reach out again and ask from her side where we could actually have the biggest impact regarding help
- I was tasked to brainstorm with all of you regarding what the community could do (I will open a new issue for that)

**Comment by J0WI** [comment]
> (it might have the best impact if we publish after June 5th)

Disagree. Blog post should be published after the holidays in the end of August/Begin of September.
Otherwise nobody will remember the post during the votes.

**Comment by MichaelKohler** [comment]
> Disagree. Blog post should be published after the holidays in the end of August/Begin of September.
> Otherwise nobody will remember the post during the votes.

That was a "certainly not before that date". August/begin of September sounds good to me!
